name: Actions Workflow

# on: [push, pull_request]

on: 
  push:
    # filter pattern cheat sheet
    # https://docs.github.com/cn/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
    branches:
      - master
      - "feature/*" # match feature/featA, feature/featB, dosn't match feature/feat/a 
      - "feature/**" # match feature/feat/a, feature/featA
      - "!feature/featC" # ignore feature/featC
    # tags: 
    #   - v1.*
    # paths: 
    #   - "**.js"
      # - "!filenane.js" # ignore
    # paths-ignore:
        # - 'docs/**'
  # repository_dispatch文档 https://docs.github.com/cn/actions/using-workflows/events-that-trigger-workflows#repository_dispatch
  # repository_dispatch:
  #   # 自定义类型
  #   types: [build]
  # schedule:
    # 分钟 小时 几号 几月 哪天
    # https://docs.github.com/cn/actions/using-workflows/events-that-trigger-workflows
    # https://crontab.guru/ cron工具
    # - cron: "5 * * * *" # 意味每小时的第五分钟执行
    # - cron: "0/5 * * * *" # 意味着每五分钟执行一次
  # push:
  pull_request:
    # 监听不同的状态
    types: [ closed, assigned, opened, reopened ]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v1
      # checkout 之后可以运行一些测试，构建的东西
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
      - name: Simple Js Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: 'inkkk'
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}" 